### ISSUE TITLE
select queries for non nullable types generate nullable types

### ISSUE THREAD

**Issue by mudrz** [adelsz/pgtyped#131] opened 2020-07-20 17:56 UTC
possibly related to https://github.com/adelsz/pgtyped/issues/130

when you have a table
```sql
CREATE TABLE untitled_table (
    id SERIAL PRIMARY KEY,
    a text,
    b text NOT NULL
);
```

a query like this:
```sql
/*
  @name GetB
*/
SELECT id FROM public.untitled_table
WHERE b = :b;
```

generates

```ts
export interface IGetBParams {
  b: string | null | void;
}
```

where b is `null` or `void`, it should probably be
```ts
export interface IGetBParams {
  b: string;
}
```

**Comment by adelsz** [comment] 2020-07-21 23:11
Duplicate of #118 
Unfortunately this is a limitation of the Postgres type inference interface.

**Closed by adelsz** 2020-07-21 23:11 UTC
